name: smart_home_assistant_iot
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  dio: ^5.8.0+1
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_switch: ^0.3.2
  iconify_flutter: ^0.0.7
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
